nelmio_cors:
  defaults:
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'x-api-token']
    expose_headers: ['Authorization']
    max_age: 3600
    hosts: []
  paths:
    '^/api/':
      allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
      allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
      allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'x-api-token']
      expose_headers: ['Authorization']
