version: '3.8'
services:
  php:
    image: php:8.1-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php
      - mailpit
      - api-doc

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp_securisation
    ports:
      - "3306:3306"

  api-doc:
    image: redocly/redoc
    ports:
      - "8080:80"
    environment:
      - SPEC_URL=/doc/specifications.yaml
    volumes:
      - ./doc/specifications.yaml:/usr/share/nginx/html/doc/specifications.yaml

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
